const unitList = [
  'acre',
  'bit',
  'byte',
  'celsius',
  'centimeter',
  'day',
  'degree',
  'fahrenheit',
  'fluid-ounce',
  'foot',
  'gallon',
  'gigabit',
  'gigabyte',
  'gram',
  'hectare',
  'hour',
  'inch',
  'kilobit',
  'kilobyte',
  'kilogram',
  'kilometer',
  'kilometer-per-hour',
  'liter',
  'megabit',
  'megabyte',
  'meter',
  'mile',
  'mile-scandinavian',
  'milliliter',
  'millimeter',
  'millisecond',
  'minute',
  'month',
  'ounce',
  'percent',
  'petabyte',
  'pound',
  'second',
  'stone',
  'terabit',
  'terabyte',
  'week',
  'yard',
  'year',
]

const currencyList = ['EUR', 'JPY', 'GBP', 'USD']
const unitListDisplay = ['short', 'long', 'narrow']
const currencyListDisplay = ['symbol', 'name', 'code']

module.exports = {
  unitList,
  currencyList,
  unitListDisplay,
  currencyListDisplay
}